export type StackChanUserServiceOptions = {
  description?: string
  nodePath: string
  cliPath: string
  deviceId: string
  socketPath?: string
}

export const GENERATED_UNIT_MARKER =
  '# Generated by @stack-chan/codex-voice-bridge'

export type SystemctlRunner = (args: string[]) => Promise<void>

export function buildStackChanUserServiceUnit(
  options: StackChanUserServiceOptions,
): string {
  const args = [
    options.nodePath,
    options.cliPath,
    'run',
    '--device-id',
    options.deviceId,
    ...(options.socketPath ? ['--socket', options.socketPath] : []),
  ]
  return `${GENERATED_UNIT_MARKER}
[Unit]
Description=${options.description ?? 'Stack-chan Codex voice bridge'}

[Service]
Type=simple
ExecStart=${args.map(systemdQuote).join(' ')}
Restart=on-failure
RestartSec=2
TimeoutStopSec=15

[Install]
WantedBy=default.target
`
}

export async function enableAndStartUserService(
  unitName: string,
  runSystemctl: SystemctlRunner,
): Promise<void> {
  validateSystemdUnitName(unitName)
  await runSystemctl(['--user', 'daemon-reload'])
  await runSystemctl(['--user', 'enable', '--now', unitName])
  await runSystemctl(['--user', 'is-active', '--quiet', unitName])
}

export function validateSystemdUnitName(value: string): string {
  if (!/^[A-Za-z0-9_.@-]+\.service$/.test(value)) {
    throw new Error(
      'unit name must contain only A-Z, a-z, 0-9, _, ., @, or - and end in .service',
    )
  }
  return value
}

function systemdQuote(value: string): string {
  const escaped = value
    .replaceAll('\\', '\\\\')
    .replaceAll('"', '\\"')
    .replaceAll('\n', '\\n')
    .replaceAll('\r', '\\r')
    .replaceAll('\t', '\\t')
    .replaceAll('$', () => '$$')
    .replaceAll('%', '%%')
  return `"${escaped}"`
}
