import assert from 'node:assert/strict'
import { spawnSync } from 'node:child_process'
import { stat } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import test from 'node:test'

test('built CLIs are executable on POSIX', async () => {
  if (process.platform === 'win32') return

  for (const path of [
    '../src/cli.js',
    '../src/service/install-user-service.js',
    '../src/applet/install-status-applet.js',
    '../src/applet/status-applet.js',
  ]) {
    const metadata = await stat(new URL(path, import.meta.url))
    assert.notEqual(metadata.mode & 0o111, 0, `${path} is not executable`)
  }
})

test('service installer dry-run does not require a workspace, device, or voice processor', () => {
  const installer = fileURLToPath(
    new URL('../src/service/install-user-service.js', import.meta.url),
  )
  const isolatedConfigHome = join(
    tmpdir(),
    `stackchan-dry-run-${process.pid}-${Date.now()}`,
  )
  const result = spawnSync(
    process.execPath,
    [installer, '--dry-run', '--port', '/definitely/missing/ttyACM'],
    {
      encoding: 'utf8',
      env: { ...process.env, XDG_CONFIG_HOME: isolatedConfigHome },
    },
  )

  assert.equal(result.status, 0, result.stderr)
  assert.match(result.stdout, /^# Generated by @stack-chan\/codex-voice-bridge/m)
  assert.match(result.stdout, /^ExecStart=/m)
})
